/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClassificacaoRouteImport } from './routes/classificacao'
import { Route as IndexRouteImport } from './routes/index'

const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificacaoRoute = ClassificacaoRouteImport.update({
  id: '/classificacao',
  path: '/classificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classificacao': typeof ClassificacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/notas': typeof NotasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classificacao': typeof ClassificacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/notas': typeof NotasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classificacao': typeof ClassificacaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/notas': typeof NotasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/classificacao' | '/configuracoes' | '/notas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/classificacao' | '/configuracoes' | '/notas'
  id: '__root__' | '/' | '/classificacao' | '/configuracoes' | '/notas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassificacaoRoute: typeof ClassificacaoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  NotasRoute: typeof NotasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classificacao': {
      id: '/classificacao'
      path: '/classificacao'
      fullPath: '/classificacao'
      preLoaderRoute: typeof ClassificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassificacaoRoute: ClassificacaoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  NotasRoute: NotasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
