/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TributarioRouteImport } from './routes/tributario'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as RelatorioClienteRouteImport } from './routes/relatorio-cliente'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as FiscalRouteImport } from './routes/fiscal'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComercialRouteImport } from './routes/comercial'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ClassificacaoRouteImport } from './routes/classificacao'
import { Route as IndexRouteImport } from './routes/index'

const TributarioRoute = TributarioRouteImport.update({
  id: '/tributario',
  path: '/tributario',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioClienteRoute = RelatorioClienteRouteImport.update({
  id: '/relatorio-cliente',
  path: '/relatorio-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const FiscalRoute = FiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificacaoRoute = ClassificacaoRouteImport.update({
  id: '/classificacao',
  path: '/classificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classificacao': typeof ClassificacaoRoute
  '/clientes': typeof ClientesRoute
  '/comercial': typeof ComercialRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/empresas': typeof EmpresasRoute
  '/fiscal': typeof FiscalRoute
  '/notas': typeof NotasRoute
  '/relatorio-cliente': typeof RelatorioClienteRoute
  '/servicos': typeof ServicosRoute
  '/tributario': typeof TributarioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classificacao': typeof ClassificacaoRoute
  '/clientes': typeof ClientesRoute
  '/comercial': typeof ComercialRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/empresas': typeof EmpresasRoute
  '/fiscal': typeof FiscalRoute
  '/notas': typeof NotasRoute
  '/relatorio-cliente': typeof RelatorioClienteRoute
  '/servicos': typeof ServicosRoute
  '/tributario': typeof TributarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classificacao': typeof ClassificacaoRoute
  '/clientes': typeof ClientesRoute
  '/comercial': typeof ComercialRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/empresas': typeof EmpresasRoute
  '/fiscal': typeof FiscalRoute
  '/notas': typeof NotasRoute
  '/relatorio-cliente': typeof RelatorioClienteRoute
  '/servicos': typeof ServicosRoute
  '/tributario': typeof TributarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classificacao'
    | '/clientes'
    | '/comercial'
    | '/configuracoes'
    | '/empresas'
    | '/fiscal'
    | '/notas'
    | '/relatorio-cliente'
    | '/servicos'
    | '/tributario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classificacao'
    | '/clientes'
    | '/comercial'
    | '/configuracoes'
    | '/empresas'
    | '/fiscal'
    | '/notas'
    | '/relatorio-cliente'
    | '/servicos'
    | '/tributario'
  id:
    | '__root__'
    | '/'
    | '/classificacao'
    | '/clientes'
    | '/comercial'
    | '/configuracoes'
    | '/empresas'
    | '/fiscal'
    | '/notas'
    | '/relatorio-cliente'
    | '/servicos'
    | '/tributario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassificacaoRoute: typeof ClassificacaoRoute
  ClientesRoute: typeof ClientesRoute
  ComercialRoute: typeof ComercialRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EmpresasRoute: typeof EmpresasRoute
  FiscalRoute: typeof FiscalRoute
  NotasRoute: typeof NotasRoute
  RelatorioClienteRoute: typeof RelatorioClienteRoute
  ServicosRoute: typeof ServicosRoute
  TributarioRoute: typeof TributarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tributario': {
      id: '/tributario'
      path: '/tributario'
      fullPath: '/tributario'
      preLoaderRoute: typeof TributarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-cliente': {
      id: '/relatorio-cliente'
      path: '/relatorio-cliente'
      fullPath: '/relatorio-cliente'
      preLoaderRoute: typeof RelatorioClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiscal': {
      id: '/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof FiscalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial': {
      id: '/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classificacao': {
      id: '/classificacao'
      path: '/classificacao'
      fullPath: '/classificacao'
      preLoaderRoute: typeof ClassificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassificacaoRoute: ClassificacaoRoute,
  ClientesRoute: ClientesRoute,
  ComercialRoute: ComercialRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EmpresasRoute: EmpresasRoute,
  FiscalRoute: FiscalRoute,
  NotasRoute: NotasRoute,
  RelatorioClienteRoute: RelatorioClienteRoute,
  ServicosRoute: ServicosRoute,
  TributarioRoute: TributarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
